const departamentos = [
  { key: 1, name: "Alcaldía", level: 1, img: "img/images.png" },
  { key: 1.1, parent: 1, name: "COSOC", level: 2, img: "img/cosoc" },
  { key: 1.2, parent: 1, name: "Juzgado de Policía Local", level: 2, img: "img/juzgadodepolicialocal" },
  { key: 1.3, parent: 1, name: "Informática", level: 2, img: "img/informatica" },
  { key: 1.4, parent: 1, name: "Administración Municipal", level: 2, img: "img/administracionmunicipal" },
  { key: 1.5, parent: 1, name: "Consejo Municipal", level: 2, img: "img/consejomunicipal" },
  { key: 1.6, parent: 1, name: "Gabinete", level: 2, img: "img/gabinete" },
  { key: 1.7, parent: 1, name: "RRPP", level: 2, img: "img/rrpp" },
  { key: 1.8, parent: 1, name: "Comité Técnico Administrativo", level: 2, img: "img/comitetecnicoadministrativo" },
  { key: 2, parent: 1.4, name: "Secretaría Municipal", level: 3, img: "img/secretariamunicipal" },
  { key: 2.1, parent: 2, name: "Depto. Decretos", level: 4, img: "img/deptodecretos" },
  { key: 2.2, parent: 2.1, name: "Secretaría de Concejo", level: 4, img: "img/secretariadeconcejo" },
  { key: 2.3, parent: 2.2, name: "Oficina de Partes", level: 4, img: "img/oficinadepartes" },
  { key: 3, parent: 1.4, name: "Dirección de Control", level: 3, img: "img/direcciondecontrol" },
  { key: 3.1, parent: 3, name: "Depto. Auditoría", level: 4, img: "img/deptoauditoria" },
  { key: 4, parent: 1.4, name: "Dirección Asesoría Jurídica", level: 3, img: "img/direccionasesoriajuridica" },
  { key: 4.1, parent: 4, name: "Transparencia", level: 4, img: "img/transparencia" },
  { key: 5, parent: 1.4, name: "Dirección de Adm. y Finanzas", level: 3, img: "img/direcciondeadmfinanzas" },
  { key: 5.1, parent: 5, name: "Sección de Rentas", level: 4, img: "img/seccionderentas" },
  { key: 5.2, parent: 5.1, name: "Depto. Bienestar", level: 4, img: "img/deptobienestar" },
  { key: 5.3, parent: 5.2, name: "Presupuestos y Contabilidad", level: 4, img: "img/presupuestosycontabilidad" },
  { key: 5.4, parent: 5.3, name: "Estudios Financieros y Estadísticas", level: 4, img: "img/estudiosfinancierosyestadisticas" },
  { key: 5.5, parent: 5.4, name: "Aprovisionamiento", level: 4, img: "img/aprovisionamiento" },
  { key: 5.6, parent: 5.5, name: "Depto. Personal", level: 4, img: "img/deptopersonal" },
  { key: 6, parent: 1.4, name: "Sec. Comunal de Planificación", level: 3, img: "img/seccomunaldeplanificacion" },
  { key: 6.1, parent: 6, name: "Asesoría Urbana", level: 4, img: "img/asesoriaurbana" },
  { key: 6.2, parent: 6.1, name: "Proyectos y Planificación", level: 4, img: "img/proyectosyplanificacion" },
  { key: 7, parent: 1.4, name: "Dirección de Obras", level: 3, img: "img/direcciondeobras" },
  { key: 7.1, parent: 7, name: "Edificación y Archivo", level: 4, img: "img/edificacionyarchivo" },
  { key: 7.2, parent: 7.1, name: "Depto. Construcción y Fiscalización Técnica", level: 4, img: "img/deptoconstruccionyfiscalizaciontecnica" },
  { key: 7.3, parent: 7.2, name: "Alumbrado Público", level: 4, img: "img/alumbradopublico" },
  { key: 7.4, parent: 7.3, name: "Urbanismo", level: 4, img: "img/urbanismo" },
  { key: 8, parent: 1.4, name: "Dirección de Desarrollo Comunitario", level: 3, img: "img/direcciondesarrollocomunitario" },
  { key: 8.1, parent: 8, name: "Depto. Social", level: 4, img: "img/deptosocial" },
  { key: 8.2, parent: 8.1, name: "Depto. Gestión Comunitaria", level: 4, img: "img/deptogestioncomunitaria" },
  { key: 8.3, parent: 8.2, name: "Depto. Desarrollo Económico Local", level: 4, img: "img/deptodesarrolloeconomicolocal" },
  { key: 8.4, parent: 8.3, name: "Cultura", level: 4, img: "img/cultura" },
  { key: 8.5, parent: 8.4, name: "Depto. de la Mujer", level: 4, img: "img/deptodelamujer" },
  { key: 8.6, parent: 8.5, name: "Depto. Riesgos de Desastres", level: 4, img: "img/deptoriesgosdesastres" },
  { key: 9, parent: 1.4, name: "Dirección de Servicios Traspasados", level: 3, img: "img/direccionserviciostraspasados" },
  { key: 9.1, parent: 9, name: "Depto. de Educación Municipal", level: 4, img: "img/deptoeducacionmunicipal" },
  { key: 9.2, parent: 9.1, name: "COSAM", level: 4, img: "img/cosam" },
  { key: 10, parent: 1.4, name: "Dirección de Operación y Servicios a la Comunidad", level: 3, img: "img/direccionoperacionyserviciosalacomunidad" },
  { key: 10.1, parent: 10, name: "Depto. de Servicios Generales", level: 4, img: "img/deptoserviciosgenerales" },
  { key: 10.2, parent: 10.1, name: "Servicio de Guardia Interna", level: 4, img: "img/serviciodeguardiainterna" },
  { key: 10.3, parent: 10.2, name: "Depto. de Emergencia", level: 4, img: "img/deptodeemergencia" },
  { key: 10.4, parent: 10.3, name: "OIRS", level: 4, img: "img/oirs" },
  { key: 11, parent: 1.4, name: "Dirección de Medio Ambiente y Áreas Verdes", level: 3, img: "img/direcciondemedioambienteyareasverdes" },
  { key: 11.1, parent: 11, name: "Depto. de Servicios Municipales", level: 4, img: "img/deptoserviciosmunicipales" },
  { key: 11.2, parent: 11.1, name: "Depto. Medio Ambiente", level: 4, img: "img/deptomedioambiente" },
  { key: 11.3, parent: 11.2, name: "Depto. Areas Verdes", level: 4, img: "img/deptoareasverdes" },
  { key: 12, parent: 1.4, name: "Dirección de Tránsito y Transporte Público", level: 3, img: "img/direcciondetransitoytransportepublico" },
  { key: 12.1, parent: 12, name: "Depto. Permisos de Circulación", level: 4, img: "img/deptopermisosdecirculacion" },
  { key: 12.2, parent: 12.1, name: "Depto. Ingeniería y Estudios", level: 4, img: "img/deptoingenieriayestudios" },
  { key: 12.3, parent: 12.2, name: "Depto. Licencias de Conducir", level: 4, img: "img/deptolicenciasdeconducir" },
  { key: 13, parent: 1.4, name: "Dirección de Seguridad Pública", level: 3, img: "img/direcciondeseguridadpublica" }
];

// export default departamentos;