const departamentos = [
  
    { key: 1, name: "Alcaldía", level: 1, img: "img/alcaldia", descripcion: "" },
    { key: 1.1, name: "COSOC", level: 2, img: "img/cosoc", descripcion: "", location: "300 100"  },
    { key: 1.2, name: "Juzgado de Policía Local", level: 2, img: "img/juzgadodepolicialocal", descripcion: "" },
    { key: 1.3, name: "Informática", level: 2, img: "img/informatica", descripcion: "" },
    { key: 1.4, name: "Administración Municipal", level: 2, img: "img/administracionmunicipal", descripcion: "" },
    { key: 1.5, name: "Consejo Municipal", level: 2, img: "img/consejomunicipal", descripcion: "" },
    { key: 1.6, name: "Gabinete", level: 2, img: "img/gabinete", descripcion: "" },
    { key: 1.7, name: "RRPP", level: 2, img: "img/rrpp", descripcion: "" },
    { key: 1.8, name: "Comité Técnico Administrativo", level: 2, img: "img/comitetecnicoadministrativo", descripcion: "" },
    { key: 2, name: "Secretaría Municipal", level: 3, img: "img/secretariamunicipal", descripcion: "" },
    { key: 2.1, name: "Depto. Decretos", level: 4, img: "img/deptodecretos", descripcion: "" },
    { key: 2.2, name: "Secretaría de Concejo", level: 4, img: "img/secretariadeconcejo", descripcion: "" },
    { key: 2.3, name: "Oficina de Partes", level: 4, img: "img/oficinadepartes", descripcion: "" },
    { key: 3, name: "Dirección de Control", level: 3, img: "img/direcciondecontrol", descripcion: "" },
    { key: 3.1, name: "Depto. Auditoría", level: 4, img: "img/deptoauditoria", descripcion: "" },
    { key: 4, name: "Dirección Asesoría Jurídica", level: 3, img: "img/direccionasesoriajuridica", descripcion: "" },
    { key: 4.1, name: "Transparencia", level: 4, img: "img/transparencia", descripcion: "" },
    { key: 5, name: "Dirección de Adm. y Finanzas", level: 3, img: "img/direcciondeadmfinanzas", descripcion: "" },
    { key: 5.1, name: "Sección de Rentas", level: 4, img: "img/seccionderentas", descripcion: "" },
    { key: 5.2, name: "Depto. Bienestar", level: 4, img: "img/deptobienestar", descripcion: "" },
    { key: 5.3, name: "Presupuestos y Contabilidad", level: 4, img: "img/presupuestosycontabilidad", descripcion: "" },
    { key: 5.4, name: "Estudios Financieros y Estadísticas", level: 4, img: "img/estudiosfinancierosyestadisticas", descripcion: "" },
    { key: 5.5, name: "Aprovisionamiento", level: 4, img: "img/aprovisionamiento", descripcion: "" },
    { key: 5.6, name: "Depto. Personal", level: 4, img: "img/deptopersonal", descripcion: "" },
    { key: 6, name: "Sec. Comunal de Planificación", level: 3, img: "img/seccomunaldeplanificacion", descripcion: "" },
    { key: 6.1, name: "Asesoría Urbana", level: 4, img: "img/asesoriaurbana", descripcion: "" },
    { key: 6.2, name: "Proyectos y Planificación", level: 4, img: "img/proyectosyplanificacion", descripcion: "" },
    { key: 7, name: "Dirección de Obras", level: 3, img: "img/direcciondeobras", descripcion: "" },
    { key: 7.1, name: "Edificación y Archivo", level: 4, img: "img/edificacionyarchivo", descripcion: "" },
    { key: 7.2, name: "Depto. Construcción y Fiscalización Técnica", level: 4, img: "img/deptoconstruccionyfiscalizaciontecnica", descripcion: "" },
    { key: 7.3, name: "Alumbrado Público", level: 4, img: "img/alumbradopublico", descripcion: "" },
    { key: 7.4, name: "Urbanismo", level: 4, img: "img/urbanismo", descripcion: "" },
    { key: 8, name: "Dirección de Desarrollo Comunitario", level: 3, img: "img/direcciondesarrollocomunitario", descripcion: "" },
    { key: 8.1, name: "Depto. Social", level: 4, img: "img/deptosocial", descripcion: "" },
    { key: 8.2, name: "Depto. Gestión Comunitaria", level: 4, img: "img/deptogestioncomunitaria", descripcion: "" },
    { key: 8.3, name: "Depto. Desarrollo Económico Local", level: 4, img: "img/deptodesarrolloeconomicolocal", descripcion: "" },
    { key: 8.4, name: "Cultura", level: 4, img: "img/cultura", descripcion: "" },
    { key: 8.5, name: "Depto. de la Mujer", level: 4, img: "img/deptodelamujer", descripcion: "" },
    { key: 8.6, name: "Depto. Riesgos de Desastres", level: 4, img: "img/deptoriesgosdesastres", descripcion: "" },
    { key: 9, name: "Dirección de Servicios Traspasados", level: 3, img: "img/direccionserviciostraspasados", descripcion: "" },
    { key: 9.1, name: "Depto. de Educación Municipal", level: 4, img: "img/deptoeducacionmunicipal", descripcion: "" },
    { key: 9.2, name: "COSAM", level: 4, img: "img/cosam", descripcion: "" },
    { key: 10, name: "Dirección de Operación y Servicios a la Comunidad", level: 3, img: "img/direccionoperacionyserviciosalacomunidad", descripcion: "" },
    { key: 10.1, name: "Depto. de Servicios Generales", level: 4, img: "img/deptoserviciosgenerales", descripcion: "" },
    { key: 10.2, name: "Servicio de Guardia Interna", level: 4, img: "img/serviciodeguardiainterna", descripcion: "" },
    { key: 10.3, name: "Depto. de Emergencia", level: 4, img: "img/deptodeemergencia", descripcion: "" },
    { key: 10.4, name: "OIRS", level: 4, img: "img/oirs", descripcion: "" },
    { key: 11, name: "Dirección de Medio Ambiente y Áreas Verdes", level: 3, img: "img/direcciondemedioambienteyareasverdes", descripcion: "" },
    { key: 11.1, name: "Depto. de Servicios Municipales", level: 4, img: "img/deptoserviciosmunicipales", descripcion: "" },
    { key: 11.2, name: "Depto. Medio Ambiente y Areas Verdes", level: 4, img: "img/deptomedioambienteyareasverdes", descripcion: "" },
	{ key: 11.3, name: "Depto. Areas Verdes", level: 4, img: "img/deptoareasverdes", descripcion: "" },
    { key: 12, name: "Dirección de Tránsito y Transporte Público", level: 3, img: "img/direcciondetransitoytransportepublico", descripcion: "" },
    { key: 12.1, name: "Depto. Permisos de Circulación", level: 4, img: "img/deptopermisosdecirculacion", descripcion: "" },
    { key: 12.2, name: "Depto. Ingeniería y Estudios", level: 4, img: "img/deptoingenieriayestudios", descripcion: "" },
    { key: 12.3, name: "Depto. Licencias de Conducir", level: 4, img: "img/deptolicenciasdeconducir", descripcion: "" },
    { key: 13, name: "Dirección de Seguridad Pública", level: 3, img: "img/direcciondeseguridadpublica", descripcion: "" }
  ];
 const links = [
    { from: 1, to: 1.4 },
    { from: 1.4, to: 2 },
    { from: 2, to: 2.1 },
    { from: 2.1, to: 2.2 },
    { from: 2.2, to: 2.3 },
    { from: 1.4, to: 3 },
    { from: 3, to: 3.1 },
    { from: 1.4, to: 4 },
    { from: 4, to: 4.1 },
    { from: 1.4, to: 5 },
    { from: 5, to: 5.1 },
    { from: 5.1, to: 5.2 },
    { from: 5.2, to: 5.3 },
    { from: 5.3, to: 5.4 },
    { from: 5.4, to: 5.5 },
    { from: 5.5, to: 5.6 },
    { from: 1.4, to: 6 },
    { from: 6, to: 6.1 },
    { from: 6.1, to: 6.2 },
    { from: 1.4, to: 7 },
    { from: 7, to: 7.1 },
    { from: 7.1, to: 7.2 },
    { from: 7.2, to: 7.3 },
    { from: 7.3, to: 7.4 },
    { from: 1.4, to: 8 },
    { from: 8, to: 8.1 },
    { from: 8.1, to: 8.2 },
    { from: 8.2, to: 8.3 },
    { from: 8.3, to: 8.4 },
    { from: 8.4, to: 8.5 },
    { from: 8.5, to: 8.6 },
    { from: 1.4, to: 9 },
    { from: 9, to: 9.1 },
    { from: 9.1, to: 9.2 },
    { from: 1.4, to: 10 },
    { from: 10, to: 10.1 },
    { from: 10.1, to: 10.2 },
    { from: 10.2, to: 10.3 },
    { from: 10.3, to: 10.4 },
    { from: 1.4, to: 11 },
    { from: 11, to: 11.1 },
    { from: 11.1, to: 11.2 },
	{ from: 11.2, to: 11.3 },
    { from: 1.4, to: 12 },
    { from: 12, to: 12.1 },
    { from: 12.1, to: 12.2 },
    { from: 12.2, to: 12.3 },
    { from: 1.4, to: 13 }
  
];







